### ISSUE TITLE
Mockuping multiple images at once

### ISSUE THREAD

**Issue by MarvinRucinski** [oursky/mockuphone.com#69] opened 2024-07-05 13:36 UTC
When trying to mockup multiple images at once through the online site mockuphone.com only the last image gets mocked up and downloaded

**Comment by pkong-ds** [comment] 2024-07-05 13:53
Hi @MervinDelfin, Thank you very much for opening this issue.

Can you help provide some reproduction details e.g.

1. Which device did you generate mockup from?
2. What images did you upload?
3. Which browser did you use?
4. If possible, exact steps to reproduce this bug?

I just tried [iphon-15](https://mockuphone.com/model/iphone-15/) with below images, it works fine.

## Input

![iphone15](https://github.com/oursky/mockuphone.com/assets/74223769/0b771f80-3631-440e-b068-a34b9c6f7c27)
![iphone15plus](https://github.com/oursky/mockuphone.com/assets/74223769/e92a647d-5726-429a-aaaa-9820535608f7)

## Output
[apple-iphone-15-black-mockup.zip](https://github.com/user-attachments/files/16110490/apple-iphone-15-black-mockup.zip)

**Comment by MarvinRucinski** [comment] 2024-07-05 14:24
Hi, @pkong-ds 
I did some testing and found the cause.

It happens when the file name of the uploaded image is too long and there are multiple files with the same beginning. For example, uploading these two files:
`Simulator Screenshot - iPhone 15 Pro Max - 2024-06-15 at 20.53.15.png`
`Simulator Screenshot - iPhone 15 Pro Max - 2024-06-15 at 20.53.29.png`
generates the same output file:
`Simulator Screenshot - iPhone 15 Pro Max - 2024-06-15 at 20-portrait`

The file name is cut off at the end so the last image overrides the mockups generated before.
These screen shot files have names that have been automatically generated by official Apple iOS Simulator on macOS.
You should add support for longer file names or add some kind of hash at the end of each file if there are multiple files with the same beginning.

**Comment by pkong-ds** [comment] 2024-07-09 09:18
Hi @MervinDelfin, 

Thank you for your response. I'm pleased to inform you that the issue has been addressed in pull requests #70 and #71. 

As mentioned in #70, the problem was 

> Previously, filename parsing method is implemented with custom code like `split('.')` instead of [`os.path.splitext()`](https://docs.python.org/3/library/os.path.html#os.path.splitext)

Your effort in reporting this issue is greatly appreciated. Feedback from users like you helps us improve our product continuously.

Please feel free to let me know if you continue to experience this problem. I would be glad to assist you further.

**Closed as completed** 2024-07-09 09:32 UTC
Labels: bug/critical, reported by users
